language: node_js
node_js:
  - "node"
  - "4"
  - "0.12"
os:
  - linux
  - osx
install:
  - npm install;
    if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_NODE_VERSION" == "node" ]; then
    npm install codecov;
    npm install codacy-coverage;
    npm install coveralls;
    npm install travis-github-lint-status;
    fi;
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_NODE_VERSION" == "node" ]; then
    ./node_modules/travis-github-lint-status/index.js;
    fi;
    npm run coverage;
after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_NODE_VERSION" == "node" ]; then
    ./node_modules/.bin/codecov;
    cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage;
    cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js;
    fi;
