language: node_js
node_js:
  - "node"
  - "4.3"
  - "0.12"
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash;
