language: node_js
env:
  - NODE_VERSION="node"
  - NODE_VERSION="6"
  - NODE_VERSION="4"
  - NODE_VERSION="0.12"
os:
  - linux
  - osx
install:
  - npm install;
    npm install codecov;
    npm install codacy-coverage;
    npm install coveralls;
script:
  - npm run coverage
after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$NODE_VERSION" == "node" ]; then
    ./node_modules/.bin/codecov;
    cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage;
    cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js;
    fi;
